### ISSUE TITLE
Script fails when invoked via nohup

### ISSUE THREAD

**Issue by Alphakilo** [jbags81/fabric-home-assistant#1]
[`nohup`](http://linux.die.net/man/1/nohup) is a nifty way to continue command executions after exiting the parent shell.
Unfortunately, the script breaks when invoked like this:

`nohup bash hass_rpi_installer.sh &`

Here's what happens on STDOUT / -ERR:

```
Hit http://mirror.de.leaseweb.net jessie InRelease
Hit http://archive.raspberrypi.org jessie InRelease
Hit http://mirror.de.leaseweb.net jessie/main armhf Packages
Hit http://mirror.de.leaseweb.net jessie/contrib armhf Packages
Hit http://archive.raspberrypi.org jessie/main armhf Packages
Hit http://mirror.de.leaseweb.net jessie/non-free armhf Packages
Hit http://mirror.de.leaseweb.net jessie/rpi armhf Packages
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Ign http://mirror.de.leaseweb.net jessie/contrib Translation-en_GB
Ign http://mirror.de.leaseweb.net jessie/contrib Translation-en
Ign http://mirror.de.leaseweb.net jessie/main Translation-en_GB
Ign http://mirror.de.leaseweb.net jessie/main Translation-en
Ign http://mirror.de.leaseweb.net jessie/non-free Translation-en_GB
Ign http://mirror.de.leaseweb.net jessie/non-free Translation-en
Ign http://mirror.de.leaseweb.net jessie/rpi Translation-en_GB
Ign http://mirror.de.leaseweb.net jessie/rpi Translation-en
Reading package lists...
Checking for python-dev: install ok installed
Checking for python-pip: install ok installed
Checking for python-pip: install ok installed
Requirement already satisfied (use --upgrade to upgrade): fabric in /usr/local/lib/python2.7/dist-packages
Cleaning up...
Cloning into 'fabric-home-assistant'...
[localhost] Executing task 'deploy'

    ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,,,,,,,, ,,,,,,,,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,,,,,,,   ,,,,,,,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,,,,,,     ,,,,,,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,,,,,       ,,,,,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,,,,         ,,,,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,,,           ,,,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,,             ,,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,               ,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,       ,,,,.     ,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,       ,,,,,,,     ,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,       ,,,,,,,,,     ,,,     ,,,,,,,,,,
    ,,,,,,,,,,,,,,,,        ,,,   ,,,      ,,     ,,,,,,,,,,
    ,,,,,,,,,,,,,,,         ,,,   ,,,       ,     ,,,,,,,,,,
    ,,,,,,,,,,,,,,          ,,,   ,,,             ,,,,,,,,,,
    ,,,,,,,,,,,,,            ,,,,,,,              ,,,,,,,,,,
    ,,,,,,,,,,,,              ,,,,,               ,,,,,,,,,,
    ,,,,,,,,,,,                ,,,                ,,,,,,,,,,
    ,,,,,,,,,,                 ,,,                 ,,,,,,,,,
    ,,,,,,,,,        ,,,       ,,,       ,,,        ,,,,,,,,
    ,,,,,,,,       ,,,,,,,     ,,,     ,,,,,,,       ,,,,,,,
    ,,,,,,,       ,,,,,,,,,    ,,,    ,,,,,,,,,       ,,,,,,
    ,,,,,,        ,,,   ,,,    ,,,    ,,,   ,,,        ,,,,,
    ,,,,,         ,,,   ,,,    ,,,    ,,,   ,,,         ,,,,
    ,,,,,,,,,,,   ,,,   ,,,    ,,,    ,,,   ,,,   ,,,,,,,,,,
    ,,,,,,,,,,,    ,,,,,,,,    ,,,    ,,,,,,,,    ,,,,,,,,,,
    ,,,,,,,,,,,      ,,,,,,    ,,,    ,,,,,,      ,,,,,,,,,,
    ,,,,,,,,,,,        ,,,,,   ,,,   ,,,,,        ,,,,,,,,,,
    ,,,,,,,,,,,          ,,,, ,,,, ,,,,,          ,,,,,,,,,,
    ,,,,,,,,,,,           ,,,, ,,, ,,,,           ,,,,,,,,,,
    ,,,,,,,,,,,            ,,,,,,,,,,,            ,,,,,,,,,,
    ,,,,,,,,,,,             ,,,,,,,,,             ,,,,,,,,,,
    ,,,,,,,,,,,              ,,,,,,,              ,,,,,,,,,,
    ,,,,,,,,,,,               ,,,,,               ,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
    ,,,,,,,,,,,                                   ,,,,,,,,,,
    ,,,,,,,,,,,   Welcome to the Home Assistant   ,,,,,,,,,,
    ,,,,,,,,,,, Raspberry Pi All-In-One Installer ,,,,,,,,,,
    ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

Your Raspberry Pi will reboot when the installer is complete.
Install is starting...
[localhost] sudo: apt-get update
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 745, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/pi/fabric-home-assistant/fabfile.py", line 260, in deploy
    update_upgrade()
  File "/home/pi/fabric-home-assistant/fabfile.py", line 71, in update_upgrade
    sudo("apt-get update")
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 677, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/operations.py", line 1146, in sudo
    capture_buffer_size=capture_buffer_size,
  File "/usr/local/lib/python2.7/dist-packages/fabric/operations.py", line 931, in _run_command
    capture_buffer_size=capture_buffer_size)
  File "/usr/local/lib/python2.7/dist-packages/fabric/operations.py", line 813, in _execute
    worker.raise_if_needed()
  File "/usr/local/lib/python2.7/dist-packages/fabric/thread_handling.py", line 12, in wrapper
    callable(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/io.py", line 229, in input_loop
    byte = msvcrt.getch() if win32 else sys.stdin.read(1)
IOError: [Errno 9] Bad file descriptor
Disconnecting from localhost... done.
```

**Comment by Landrash** [comment]
@Alphakilo I'm not certain this is the case but `nohup` in general does by default not work with `sudo` commands.

In this case it shouldn't really be a problem since this is most likely run once.
