### ISSUE TITLE
All in one installer fails to install

### ISSUE THREAD

**Issue by chrom3** [jbags81/fabric-home-assistant#18]
Raspberry pi 2
2016-05-27-raspbian-jessie 4.4
python 3.4.2

**Traceback:**

``` bash
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 666, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 167, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/home/pi/fabric-home-assistant/fabfile.py", line 177
    fabric.contrib.files.append("/home/hass/.homeassistant/configuration.yaml", hacfg, use_sudo=True)
         ^
SyntaxError: invalid syntax
```

**Additional info:**
When trying to install the all in one script I get this error and the installation stops.
2 days ago when it was HASS 0.24.1 it worked perfectly on the same raspberry pi.

I tried another SD-card but had the same effect.

The only thing I did before running:

``` bash
$ wget -Nnv https://raw.githubusercontent.com/home-assistant/fabric-home-assistant/master/hass_rpi_installer.sh && bash hass_rpi_installer.sh
```

was expand the filesystem, change the password and change the timezone.

I did these actions 2 days ago too.

**Comment by chrom3** [comment]
I guess it is fixed.
