### ISSUE TITLE
Installation fails with error importing SSH library

### ISSUE THREAD

**Issue by fdomig** [jbags81/fabric-home-assistant#34]
Running the installer on a fresh installed RaspberryPi 2 with this command:

```
wget -Nnv https://raw.githubusercontent.com/home-assistant/fabric-home-assistant/master/hass_rpi_installer.sh && bash hass_rpi_installer.sh
```

Results in the following error (in `installation_report.txt`):

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 24, in <module>
    import paramiko as ssh
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 33, in <module>
    from cryptography.hazmat.backends import default_backend
ImportError: No module named cryptography.hazmat.backends

There was a problem importing our SSH library (see traceback above).
Please make sure all dependencies are installed and importable.
```

**Comment by fdomig** [comment]
This seem to fix this issue

```
sudo apt-get install libffi-dev libssl-dev
sudo pip install cryptography --force-reinstall
```

**Comment by patchedsoul** [comment]
root issue was due to aged pip and inability to build dependencies as a result. resolved in latest fixes.
