### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u2018' 

### ISSUE THREAD

**Issue by basveeling** [jbags81/fabric-home-assistant#38]
I'm getting the following error while running the installer on a raspberry pi 1 B. Any ideas?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/fabric/main.py", line 762, in main
    *args, **kwargs
  File "/usr/local/lib/python3.4/dist-packages/fabric/tasks.py", line 385, in execute
    multiprocessing
  File "/usr/local/lib/python3.4/dist-packages/fabric/tasks.py", line 275, in _execute
    return task.run(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/fabric/tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "/home/pi/fabric-home-assistant/fabfile.py", line 308, in deploy
    setup_dirs()
  File "/home/pi/fabric-home-assistant/fabfile.py", line 87, in setup_dirs
    sudo("mkdir homeassistant")
  File "/usr/local/lib/python3.4/dist-packages/fabric/network.py", line 682, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/fabric/operations.py", line 1149, in sudo
    capture_buffer_size=capture_buffer_size,
  File "/usr/local/lib/python3.4/dist-packages/fabric/operations.py", line 934, in _run_command
    capture_buffer_size=capture_buffer_size)
  File "/usr/local/lib/python3.4/dist-packages/fabric/operations.py", line 816, in _execute
    worker.raise_if_needed()
  File "/usr/local/lib/python3.4/dist-packages/fabric/thread_handling.py", line 26, in raise_if_needed
    six.reraise(e[0], e[1], e[2])
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/fabric/thread_handling.py", line 13, in wrapper
    callable(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/fabric/io.py", line 31, in output_loop
    OutputLooper(*args, **kwargs).loop()
  File "/usr/local/lib/python3.4/dist-packages/fabric/io.py", line 161, in loop
    self._flush(printable_bytes)
  File "/usr/local/lib/python3.4/dist-packages/fabric/io.py", line 52, in _flush
    self.stream.write(text)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2018' in position 24: ordinal not in range(128)
Disconnecting from localhost... done.
```

**Comment by dale3h** [comment]
Please check your system locale using `sudo raspi-config` and make sure that the default generated is C_UTF.

**Comment by basveeling** [comment]
It seems that ITerm2 was setting the locale automatically when logging into the pi with ssh, to an uninstalled locale. See: http://askubuntu.com/questions/599808/cannot-set-lc-ctype-to-default-locale-no-such-file-or-directory/778672#778672. Thanks for the tip regarding locale!
