### ISSUE TITLE
Front-end does not load after AiO Installation

### ISSUE THREAD

**Issue by devanl** [jbags81/fabric-home-assistant#49]
After install I am unable to load the front-end.  Inspection of the configuration.yaml shows that only mqtt settings are present.

Adding the following to the configuration.yaml
```
http:
  api_password: xxxxx
  server_port: 443
  ssl_certificate: /etc/letsencrypt/live/xx.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/xx.duckdns.org/privkey.pem
```
From there I manually start HA as follows:
```
(homeassistant_venv) pi@raspberrypi:/etc/letsencrypt $  sudo /srv/homeassistant/homeassistant_venv/bin/python3 /srv/homeassistant/homeassistant_venv/bin/hass -c /home/homeassistant/.homeassistant
```
The system appears to start up but then when I point my browser at it I get:
```
ERROR:homeassistant.core:Error doing job: Fatal read error on SSL transport
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 825, in _read_ready
    data = self._sock.recv(self.max_size)
  File "/usr/lib/python3.4/ssl.py", line 730, in recv
    return self.read(buflen)
  File "/usr/lib/python3.4/ssl.py", line 619, in read
    v = self._sslobj.read(len or 1024)
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1769)
```
And the browser returns 404: Not Found

There is possibly one error in the log but it looks like the install was not interrupted:
```
[localhost] out: Searching for gevent-socketio>=0.3.6
[localhost] out: Reading https://pypi.python.org/simple/gevent-socketio/
[localhost] out: Downloading https://pypi.python.org/packages/57/8f/16b508f602cff2dd506636b8d415e39cacb3400d49e885f002bf6436a777/gevent-socketio-0.3.6.tar.gz#md5=33f745d74885366a07da516c000854b6
[localhost] out: Best match: gevent-socketio 0.3.6
[localhost] out: Processing gevent-socketio-0.3.6.tar.gz
[localhost] out: Writing /tmp/easy_install-mt4m1toa/gevent-socketio-0.3.6/setup.cfg
[localhost] out: Running gevent-socketio-0.3.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-mt4m1toa/gevent-socketio-0.3.6/egg-dist-tmp-tu4sqjfz
[localhost] out: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/setuptools/dist.py:342: UserWarning: The version specified (':versiontools:versiontools') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
[localhost] out:   "details." % self.metadata.version
[localhost] out:
[localhost] out: Installed /tmp/easy_install-mt4m1toa/gevent-socketio-0.3.6/.eggs/versiontools-1.9.1-py3.4.egg
[localhost] out: warning: no previously-included files found matching 'socketio/.ropeproject/*'
[localhost] out: warning: no previously-included files found matching 'socketio/sample_protocol_for_doc.py'
[localhost] out:   File "build/bdist.linux-armv7l/egg/socketio/namespace.py", line 170
[localhost] out:     print "ERROR: No such callback for ackId %s" % packet['ackId']
[localhost] out:                                                ^
[localhost] out: SyntaxError: Missing parentheses in call to 'print'
[localhost] out:
[localhost] out:   File "build/bdist.linux-armv7l/egg/socketio/server.py", line 108
[localhost] out:     except error, ex:
[localhost] out:                 ^
[localhost] out: SyntaxError: invalid syntax
[localhost] out:
[localhost] out:   File "build/bdist.linux-armv7l/egg/socketio/virtsocket.py", line 365
[localhost] out:     except (ValueError, KeyError, Exception), e:
[localhost] out:                                             ^
[localhost] out: SyntaxError: invalid syntax
[localhost] out:
[localhost] out:   File "build/bdist.linux-armv7l/egg/socketio/packet.py", line 156
[localhost] out:     except ValueError, e:
[localhost] out:                      ^
[localhost] out: SyntaxError: invalid syntax
[localhost] out:
[localhost] out: zip_safe flag not set; analyzing archive contents...
[localhost] out: socketio.__pycache__.sdjango.cpython-34: module references __path__
[localhost] out: creating /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/gevent_socketio-0.3.6-py3.4.egg
[localhost] out: Extracting gevent_socketio-0.3.6-py3.4.egg to /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages
[localhost] out:   File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/gevent_socketio-0.3.6-py3.4.egg/socketio/namespace.py", line 170
[localhost] out:     print "ERROR: No such callback for ackId %s" % packet['ackId']
[localhost] out:                                                ^
[localhost] out: SyntaxError: Missing parentheses in call to 'print'
[localhost] out:
[localhost] out:   File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/gevent_socketio-0.3.6-py3.4.egg/socketio/server.py", line 108
[localhost] out:     except error, ex:
[localhost] out:                 ^
[localhost] out: SyntaxError: invalid syntax
[localhost] out:
[localhost] out:   File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/gevent_socketio-0.3.6-py3.4.egg/socketio/virtsocket.py", line 365
[localhost] out:     except (ValueError, KeyError, Exception), e:
[localhost] out:                                             ^
[localhost] out: SyntaxError: invalid syntax
[localhost] out:
[localhost] out:   File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/gevent_socketio-0.3.6-py3.4.egg/socketio/packet.py", line 156
[localhost] out:     except ValueError, e:
[localhost] out:                      ^
[localhost] out: SyntaxError: invalid syntax
[localhost] out:
[localhost] out: Adding gevent-socketio 0.3.6 to easy-install.pth file
[localhost] out:
[localhost] out: Installed /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/gevent_socketio-0.3.6-py3.4.egg
```
Is this expected?

**Comment by patchedsoul** [comment]
successfully ran and tested AiO against Raspbian Jessie-Lite (04/10/2017) image.
