### ISSUE TITLE
Install: ImportError: cannot import name 'isMappingType'

### ISSUE THREAD

**Issue by SteveEdson** [jbags81/fabric-home-assistant#57]
When installing I get the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/fab", line 7, in <module>
    from fabric.main import main
  File "/usr/local/lib/python3.4/dist-packages/fabric/main.py", line 13, in <module>
    from operator import isMappingType
ImportError: cannot import name 'isMappingType'
```

Running on:

```
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
```

**Comment by patchedsoul** [comment]
Where from, and as who, was the AiO executed? It looks to be a python 2 vs python 3 related issue as "from operator import isMappingType" will only work in a python2 env.
